# Generated by Django 5.0.6 on 2024-06-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('description', models.TextField(max_length=255, verbose_name='Описание курса')),
                ('start_date', models.DateField(verbose_name='Начало курсов')),
                ('end_date', models.DateField(verbose_name='окончание курсов')),
                ('image', models.ImageField(null=True, upload_to='static/img/company/', verbose_name='Картинка курсв')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
