# Generated by Django 5.0.6 on 2024-06-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_courses_image_lesson_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/lesson/', verbose_name='Картинка урока'),
        ),
        migrations.AddField(
            model_name='content',
            name='link',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='content',
            name='text',
            field=models.TextField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=255, null=True, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='end_date',
            field=models.DateField(null=True, verbose_name='окончание курсов'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Начало курсов'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название урока'),
        ),
    ]
