# Generated by Django 5.0.6 on 2024-06-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_content_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='content',
            new_name='material',
        ),
    ]
