# Generated by Django 5.0.6 on 2024-06-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_content_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='material',
        ),
    ]
