# Generated by Django 5.0.6 on 2024-06-06 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_delete_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, null=True, verbose_name='Текст')),
                ('image', models.ImageField(null=True, upload_to='static/img/lesson/', verbose_name='Картинка урока')),
                ('link', models.CharField(max_length=255, null=True, verbose_name='Ссылка')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
    ]
