# Generated by Django 5.0.6 on 2024-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cources/', verbose_name='Картинка курсв'),
        ),
    ]
