# Generated by Django 5.0.6 on 2024-06-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
