# Generated by Django 5.0.6 on 2024-06-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='image',
        ),
        migrations.AddField(
            model_name='material',
            name='presentation',
            field=models.FileField(null=True, upload_to='', verbose_name='Презентация'),
        ),
    ]
