# Generated by Django 5.0.6 on 2024-06-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_material_image_material_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='presentation',
            field=models.FileField(null=True, upload_to='static/presentation/', verbose_name='Презентация'),
        ),
    ]
