# Generated by Django 5.0.6 on 2024-06-22 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_material_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='presentation',
        ),
    ]
