# Generated by Django 5.0.6 on 2024-06-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_material_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='presentation',
            field=models.FileField(help_text='Загрузите файл', null=True, upload_to='static/presentation/', verbose_name='Форма проектной декларации'),
        ),
    ]
